apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ace-config-pvc
spec:
  storageClassName: ocs-external-storagecluster-ceph-rbd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Block